Repository TheStarport/FLHook, pull requests merged in 2023-02, with the labels that each got.

#163 Restructure Pipelines and fix build issues
  .github/workflows/clang.yml
  .github/workflows/docs.yaml
  .github/workflows/release.yml
  .github/workflows/sonar.yml
  sonar-project.properties
Labels: bug

#186 feat: allow save game location to be moddified
  include/Tools/Concepts.hpp
  include/Tools/Utils.hpp
  project/FLHook.vcxproj
  project/FLHook.vcxproj.filters
  source/CCmds.cpp
  source/FLHook.cpp
  source/Memory/MemoryManager.cpp
  source/Memory/MemoryManager.hpp
  source/Memory/SaveData.cpp
Labels: core

#222 Add Serializer validation
  include/FLHook.hpp
  include/Tools/Concepts.hpp
  include/Tools/Serialization/Attributes.hpp
  include/Tools/Serialization/Serializer.hpp
  include/ext/Singleton.h
  plugins/arena/Main.cpp
  plugins/bountyhunt/Main.cpp
  plugins/cash_manager/Main.cpp
  plugins/condata/Main.cpp
  plugins/condata/Main.h
  plugins/death_penalty/Main.cpp
  plugins/ip_ban/Main.cpp
  plugins/kill_tracker/Main.cpp
  plugins/light_control/Main.cpp
  plugins/mark/Main.cpp
  plugins/message/Main.cpp
  plugins/minecontrol/Main.cpp
  plugins/misc_commands/Main.cpp
  plugins/npc_control/Main.cpp
  plugins/purchase_restrictions/Main.cpp
  plugins/rename/Main.cpp
  plugins/restarts/Main.cpp
  plugins/sound_manager/Main.cpp
  plugins/spin_protection/Main.cpp
  plugins/stats/Main.cpp
  plugins/system_sensor/Main.cpp
  plugins/tax/Main.cpp
  plugins/warehouse/Main.cpp
  project/FLHook.vcxproj
  project/FLHook.vcxproj.filters
Labels: enhancement
